import {McpServer} from '@modelcontextprotocol/sdk/server/mcp.js';
import {ApiClient} from '../http/client.js';
import {registerSearchTool} from './search/index.js';
import {registerHistoriesTool} from './historical/index.js';
import {registerSummaryTool} from './summary/index.js';
import {registerProfileTool} from './profile/index.js';
import {registerNewsTool} from './news/index.js';
import {registerAnalysisAnalystsTool} from './analysis/analysts/index.js';
import {registerAnalysisEarningsTool} from './analysis/earnings/index.js';
import {registerAnalysisRecommendationsTool} from './analysis/recommendations/index.js';
import {registerAnalysisUpgradesDowngradesTool} from './analysis/upgrades-downgrades/index.js';
import {registerHoldersGeneralTool} from './holders/general/index.js';
import {registerHoldersInstitutionalTool} from './holders/institutional/index.js';
import {registerHoldersMutualFundsTool} from './holders/mutual-funds/index.js';
import {registerHoldersInsidersTool} from './holders/insiders/index.js';
import {registerHoldersInsidersTransactionsTool} from './holders/insiders-transactions/index.js';
import {registerFinancialsGeneralTool} from './financials/general/index.js';
import {registerFinancialsIncomeStatementTool} from './financials/income_statement/index.js';
import {registerFinancialsBalanceSheetTool} from './financials/balance_sheet/index.js';
import {registerFinancialsCashFlowTool} from './financials/cash_flow/index.js';
import {registerFinancialsValuationMeasuresTool} from './financials/valuation_measures/index.js';
import {registerStatisticsGeneralTool} from './statistics/general/index.js';
import {registerStatisticsRisksTool} from './statistics/risks/index.js';
import {registerStatisticsAnnualReturnsTool} from './statistics/annual-returns/index.js';
import {registerHoldingsGeneralTool} from './holdings/general/index.js';
import {registerHoldingsTopHoldingsTool} from './holdings/top-holdings/index.js';
import {registerOptionsChainTool} from './options/chain/index.js';
import {registerOptionsContractsTool} from './options/contracts/index.js';
import {registerOptionsExpirationsTool} from './options/expirations/index.js';

export function registerAllTools(server: McpServer, client: ApiClient): void {
	registerSearchTool(server, client);
	registerHistoriesTool(server, client);
	registerSummaryTool(server, client);
	registerProfileTool(server, client);
	registerNewsTool(server, client);
	registerAnalysisAnalystsTool(server, client);
	registerAnalysisEarningsTool(server, client);
	registerAnalysisRecommendationsTool(server, client);
	registerAnalysisUpgradesDowngradesTool(server, client);
	registerHoldersGeneralTool(server, client);
	registerHoldersInstitutionalTool(server, client);
	registerHoldersMutualFundsTool(server, client);
	registerHoldersInsidersTool(server, client);
	registerHoldersInsidersTransactionsTool(server, client);
	registerFinancialsGeneralTool(server, client);
	registerFinancialsIncomeStatementTool(server, client);
	registerFinancialsBalanceSheetTool(server, client);
	registerFinancialsCashFlowTool(server, client);
	registerFinancialsValuationMeasuresTool(server, client);
	registerStatisticsGeneralTool(server, client);
	registerStatisticsRisksTool(server, client);
	registerStatisticsAnnualReturnsTool(server, client);
	registerHoldingsGeneralTool(server, client);
	registerHoldingsTopHoldingsTool(server, client);
	registerOptionsChainTool(server, client);
	registerOptionsContractsTool(server, client);
	registerOptionsExpirationsTool(server, client);
}
